Repository theforeman/puppet-foreman_proxy, pull requests merged in 2018-12, with the labels that each got.

#460 namespace extlib functions
  manifests/params.pp
  manifests/plugin/dns/powerdns/params.pp
  metadata.json
Labels: Needs testing, Not yet reviewed

#469 Use modern facts and IP address validation
  manifests/proxydns.pp
  spec/classes/foreman_proxy__proxydns__spec.rb
Labels: Needs testing, Not yet reviewed

#471 Fixes #25591 - Remove $use_ranges from infoblox dhcp
  manifests/plugin/dhcp/infoblox.pp
  spec/classes/foreman_proxy__plugin__dhcp__infoblox_spec.rb
  templates/plugin/dhcp_infoblox.yml.erb
Labels: Backwards incompatible, Needs testing, Not yet reviewed

#472 Disable repository management by default
  manifests/init.pp
  manifests/install.pp
  manifests/params.pp
  spec/acceptance/basic_spec.rb
  spec/acceptance/http_spec.rb
  spec/classes/foreman_proxy__spec.rb
Labels: Backwards incompatible, Needs testing

#473 Modulesync: refactor acceptance tests + gem updates
  .travis.yml
  Gemfile
  spec/acceptance/nodesets/vagrant_libvirt/centos-6.yml
  spec/acceptance/nodesets/vagrant_libvirt/centos-7.yml
  spec/acceptance/nodesets/vagrant_libvirt/debian-8.yml
  spec/acceptance/nodesets/vagrant_libvirt/debian-9.yml
  spec/spec_helper.rb
  spec/spec_helper_acceptance.rb
Labels: Modulesync, Needs testing, Not yet reviewed
