Repository theforeman/puppet-foreman_proxy, pull requests merged in 2018-10, with the labels that each got.

#456 Fixes #25036 - ensure proxy registration happens before puppet
  manifests/register.pp
Labels: Needs re-review, Needs testing

#458 Added JOURNAL option for log_file
  manifests/init.pp
  templates/settings.yml.erb
Labels: Needs testing

#462 Mark compatible with theforeman/puppet 10.x
  metadata.json
Labels: Needs testing, Not yet reviewed

#465 Update README
  README.md
Labels: Needs testing, Not yet reviewed

#464 realm_ad: Allow using unspecified DC
  manifests/plugin/realm/ad.pp
Labels: Needs testing
