Repository theforeman/puppet-foreman_proxy, pull requests merged in 2018-03, with the labels that each got.

#412 attempt a more accurate DNS/DHCP default interface
  manifests/params.pp
Labels: Needs testing

#417 Fixes #22845 - Install python-requests with Ansible
  manifests/plugin/ansible.pp
Labels: Needs testing, Waiting on contributor

#414 Fix the documentation for the infoblox DHCP plugin
  manifests/plugin/dhcp/infoblox.pp
Labels: Needs testing, Not yet reviewed

#420 Pin facterdb to 0.5.0
  Gemfile
Labels: Needs testing, Not yet reviewed

#419 Rewrite PowerDNS support as an example
  README.md
Labels: Needs testing, Not yet reviewed

#418 Fixes #22862 - add async_ssh param
  manifests/plugin/remote_execution/ssh.pp
  manifests/plugin/remote_execution/ssh/params.pp
  spec/classes/foreman_proxy__plugin__dynflow_spec.rb
  spec/classes/foreman_proxy__plugin__remote_execution__ssh_spec.rb
  templates/plugin/remote_execution_ssh.yml.erb
Labels: Needs testing
