Repository theforeman/puppet-foreman_proxy, pull requests merged in 2019-06, with the labels that each got.

#510 Allow for non tfm- packages on Fedora and RHEL8
  manifests/plugin/dynflow.pp
  manifests/plugin/remote_execution/ssh.pp
Labels: Needs testing

#509 allow newer extlib version
  metadata.json
Labels: Needs testing, Not yet reviewed

#513 Release 11.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog
