Repository theforeman/puppet-foreman_proxy, pull requests merged in 2019-08, with the labels that each got.

#528 Re-add :puppet_version setting to puppet.yml
  spec/classes/foreman_proxy__spec.rb
  templates/puppet.yml.erb
Labels: Bug, Needs testing

#529 Release 12.0.1
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed

#531 Fixes #27552 - Fix journald logging
  examples/journald.pp
  manifests/install.pp
  spec/acceptance/journald_spec.rb
  spec/classes/foreman_proxy__spec.rb
Labels: Needs testing

#535 Release 11.1.1
  CHANGELOG.md
  metadata.json
Labels: Needs testing

#532 Remove unused setting from pulp3
  spec/classes/foreman_proxy__plugin__pulp_spec.rb
  templates/plugin/pulp3.yml.erb
Labels: Needs testing

#530 Allow configuring saltfile path for salt
  manifests/plugin/salt.pp
  manifests/plugin/salt/params.pp
  spec/classes/foreman_proxy__plugin__salt_spec.rb
  templates/plugin/salt.yml.erb
Labels: Enhancement, Needs testing, Not yet reviewed
