Repository theforeman/puppet-foreman_proxy, pull requests merged in 2019-07, with the labels that each got.

#518 Fixes #27196 - Add roles_path to ansible.cfg
  manifests/plugin/ansible.pp
  manifests/plugin/ansible/params.pp
  spec/classes/foreman_proxy__plugin__ansible_spec.rb
  templates/plugin/ansible.cfg.erb
Labels: Enhancement, Needs testing

#519 Refs #27196 - Remote empty line
  manifests/plugin/ansible.pp
Labels: Needs testing

#514 Fixes #27053 - Drop Puppet 3 support from the proxy
  manifests/config.pp
  manifests/init.pp
  manifests/params.pp
  manifests/settings_file.pp
  spec/classes/foreman_proxy__spec.rb
  templates/puppet.yml.erb
  templates/puppet_proxy_legacy.yml.erb
  templates/puppet_proxy_puppetrun.yml.erb
  templates/sudo.erb
  templates/sudo_augeas.erb
Labels: Backwards incompatible, Needs testing

#508 Move python-requests to packaging for ansible
  manifests/plugin/ansible.pp
Labels: Backwards incompatible, Needs testing

#512 Add support for external Dynflow core
  manifests/plugin/dynflow.pp
  manifests/plugin/dynflow/params.pp
  spec/classes/foreman_proxy__plugin__dynflow_spec.rb
  templates/plugin/dynflow.yml.erb
Labels: Enhancement, Needs testing

#511 Fixes #25481 - Set ProxyCommand=none for Ansible
  manifests/plugin/ansible.pp
  manifests/plugin/ansible/params.pp
  spec/classes/foreman_proxy__plugin__ansible_spec.rb
  templates/plugin/ansible.cfg.erb
Labels: Bug, Needs testing, Not yet reviewed

#515 Fixes #27264 - Install ansible-runner package
  manifests/plugin/ansible.pp
  manifests/plugin/ansible/params.pp
  manifests/plugin/ansible/runner.pp
  spec/classes/foreman_proxy__plugin__ansible_spec.rb
Labels: Needs testing

#526 Document the Ansible integration
  README.md
Labels: Needs testing, skip-changelog

#524 Release 12.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, Not yet reviewed
