Repository theforeman/puppet-foreman_proxy, pull requests merged in 2019-02, with the labels that each got.

#487 Clean up params.pp
  manifests/params.pp
Labels: Needs testing, Waiting on contributor

#490 Add a test for dns true and dns_managed false
  spec/classes/foreman_proxy__config__spec.rb
Labels: Needs testing, Not yet reviewed

#491 Rewrite foreman::config test
  spec/classes/foreman_proxy__config__spec.rb
  spec/classes/foreman_proxy__spec.rb
Labels: Needs testing, Not yet reviewed

#492 Configure ansible's stdout_callback to yaml for nicer output
  manifests/plugin/ansible.pp
  manifests/plugin/ansible/params.pp
  spec/classes/foreman_proxy__plugin__ansible_spec.rb
  templates/plugin/ansible.cfg.erb
Labels: Needs testing, Not yet reviewed

#493 Raise minimum foreman and puppet versions
  metadata.json
Labels: Needs testing
