Repository theforeman/puppet-foreman_proxy, pull requests merged in 2019-04, with the labels that each got.

#498 drop Puppet 4
  .travis.yml
  Gemfile
  metadata.json
Labels: Backwards incompatible, Needs testing

#501 Handle the sudoversion fact in modulesync
  .sync.yml
  spec/spec_helper.rb
Labels: Needs testing, Not yet reviewed

#502 Allow newest module versions
  metadata.json
Labels: Needs testing, Not yet reviewed

#486 Ensure shim permissions
  manifests/tftp/netboot.pp
  spec/classes/foreman_proxy__tftp_spec.rb
Labels: Needs testing

#503 Add pulp3 options to the pulp plugin
  manifests/plugin/pulp.pp
  manifests/plugin/pulp/params.pp
  spec/classes/foreman_proxy__plugin__pulp_spec.rb
  templates/plugin/pulp3.yml.erb
Labels: Needs testing

#504 Release 11.0.0
  CHANGELOG.md
  HISTORY.md
Labels: Needs testing, Not yet reviewed
