Repository theforeman/puppet-foreman_proxy, pull requests merged in 2020-06, with the labels that each got.

#597 replace nsupdate dependency on FreeBSD
  manifests/params.pp
  spec/classes/foreman_proxy__spec.rb
Labels: Needs testing

#600 Fixes #30121 - Generate SSH keys in PEM format
  manifests/plugin/remote_execution/ssh.pp
  spec/classes/foreman_proxy__plugin__remote_execution__ssh_spec.rb
Labels: Needs testing

#601 Release 14.0.1
  CHANGELOG.md
  metadata.json
Labels: Needs testing

#602 Fixes #30198 - Disable TFTP by default
  manifests/params.pp
  spec/classes/foreman_proxy__register__spec.rb
  spec/classes/foreman_proxy__spec.rb
Labels: Backwards incompatible, Needs testing

#603 Fixes #30240 - compat with theforeman/dns 8.x
  examples/dns.pp
  manifests/proxydns.pp
  metadata.json
  spec/acceptance/dns_spec.rb
  spec/setup_acceptance_node.pp
Labels: Bug, Needs testing
