Repository theforeman/puppet-foreman_proxy, pull requests merged in 2020-10, with the labels that each got.

#621 Do not set recursive ACLs on dhcp
  manifests/proxydhcp.pp
  spec/classes/foreman_proxy__proxydhcp__spec.rb
Labels: Needs testing

#622 Fixes #30962 - Correct DHCP file permissions
  examples/isc_dhcp.pp
  examples/isc_dhcp_omapi.pp
  manifests/proxydhcp.pp
  spec/acceptance/isc_dhcp_spec.rb
  spec/classes/foreman_proxy__proxydhcp__spec.rb
Labels: Needs testing

#625 Release 14.1.2
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing

#618 Fixes #30669 - Removing puppetrun options
  README.md
  manifests/config.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_proxy__spec.rb
  templates/puppet.yml.erb
  templates/puppet_proxy_customrun.yml.erb
  templates/puppet_proxy_mcollective.yml.erb
  templates/puppet_proxy_salt.yml.erb
  templates/puppet_proxy_ssh.yml.erb
Labels: Backwards incompatible, Needs testing

#623 Do not set ACLs on DHCP leases directory
  manifests/proxydhcp.pp
  spec/classes/foreman_proxy__proxydhcp__spec.rb
Labels: Enhancement, Needs testing

#626 Refs #29830 - Move discovery plugin docs to RDOC and split out advanced parameters
  manifests/plugin/discovery.pp
Labels: Enhancement, Needs testing

#627 15.2.1 cps
  manifests/proxydhcp.pp
  spec/classes/foreman_proxy__proxydhcp__spec.rb
Labels: Needs testing

#629 Release 15.3.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing

#619 Fixes #30950 - Enable SmartProxy Registration module
  README.md
  manifests/config.pp
  manifests/init.pp
  manifests/module/registration.pp
  manifests/params.pp
  spec/classes/foreman_proxy__register__spec.rb
  templates/registration.yml.erb
Labels: Needs testing

#631 Switch to GH Actions from Travis
  .github/workflows/acceptance.yml
  .github/workflows/cron.yml
  .github/workflows/unit.yml
  .travis.yml
Labels: Needs testing, skip-changelog

#632 Release 16.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog
