Repository theforeman/puppet-foreman_proxy, pull requests merged in 2020-03, with the labels that each got.

#566 Use HTTP in remote_file acceptance test
  spec/acceptance/foreman_remote_file_spec.rb
Labels: Needs testing, Not yet reviewed

#567 Fix chef plugin listen on
  spec/classes/foreman_proxy__plugin__chef__spec.rb
  templates/plugin/chef.yml.erb
Labels: Bug, Needs testing, Not yet reviewed

#568 Document classes using puppet-strings
  lib/puppet/functions/foreman_proxy/get_network_in_addr.rb
  manifests/config.pp
  manifests/feature.pp
  manifests/install.pp
  manifests/params.pp
  manifests/plugin.pp
  manifests/plugin/ansible/params.pp
  manifests/plugin/discovery.pp
  manifests/plugin/dynflow/params.pp
  manifests/plugin/monitoring/icingadirector/params.pp
  manifests/proxydhcp.pp
  manifests/proxydns.pp
  manifests/register.pp
  manifests/remote_file.pp
  manifests/service.pp
  manifests/settings_file.pp
  manifests/tftp.pp
  manifests/tftp/netboot.pp
  manifests/tftp/netboot/params.pp
  types/listenon.pp
Labels: Needs testing, Not yet reviewed

#571 Remove redundant parameters
  manifests/service.pp
Labels: Needs testing, Not yet reviewed

#572 Introduce foreman_proxy::globals
  manifests/config.pp
  manifests/globals.pp
  manifests/init.pp
  manifests/params.pp
  manifests/plugin.pp
  manifests/plugin/ansible.pp
  manifests/plugin/ansible/params.pp
  manifests/plugin/dynflow.pp
  manifests/plugin/monitoring/icingadirector/params.pp
  manifests/settings_file.pp
  spec/defines/foreman_proxy_plugin_spec.rb
  spec/defines/foreman_proxy_settings_file_spec.rb
Labels: Backwards incompatible, Needs testing

#573 Drop group parameter on plugins
  manifests/plugin/abrt.pp
  manifests/plugin/chef.pp
  manifests/plugin/chef/params.pp
  manifests/plugin/monitoring.pp
  manifests/plugin/omaha.pp
  manifests/plugin/pulp.pp
  manifests/plugin/pulp/params.pp
  manifests/plugin/realm/ad.pp
  manifests/plugin/salt.pp
  manifests/plugin/salt/params.pp
  spec/classes/foreman_proxy__plugin__abrt_spec.rb
  spec/classes/foreman_proxy__plugin__monitoring_spec.rb
  spec/classes/foreman_proxy__plugin__omaha_spec.rb
  spec/classes/foreman_proxy__plugin__pulp_spec.rb
  spec/classes/foreman_proxy__plugin__realm__ad_spec.rb
  spec/classes/foreman_proxy__plugin__salt_spec.rb
Labels: Backwards incompatible, Needs testing, Not yet reviewed

#575 Move Ruby package prefix to params
  manifests/params.pp
  manifests/plugin/remote_execution/ssh.pp
Labels: Needs testing, Not yet reviewed

#574 Use $f_p::plugin::dynflow::external_core
  manifests/plugin/ansible.pp
  manifests/plugin/dynflow.pp
  manifests/plugin/remote_execution/ssh.pp
  spec/classes/foreman_proxy__plugin__dynflow_spec.rb
Labels: Bug, Needs testing

#570 Declare features on SSH and Pulp modules
  manifests/plugin/pulp.pp
  manifests/plugin/remote_execution/ssh.pp
Labels: Enhancement, Needs testing

#576 re-enable dynflow acceptance test on Debian
  spec/acceptance/dynflow_spec.rb
Labels: Needs testing
