Repository theforeman/puppet-foreman_proxy, pull requests merged in 2020-04, with the labels that each got.

#577 add Ubuntu integration tests
  .sync.yml
  .travis.yml
Labels: Needs testing

#579 add support for flatcar
  manifests/plugin/omaha.pp
  templates/plugin/omaha.yml.erb
Labels: Enhancement, Needs testing

#580 Drop EPEL in acceptance tests
  .sync.yml
  spec/spec_helper_acceptance.rb
Labels: Needs testing, Not yet reviewed

#583 Refs #29213: Update shim.efi path for EL8
  manifests/tftp/netboot.pp
  spec/classes/foreman_proxy__tftp__netboot_spec.rb
Labels: Needs testing
