Repository theforeman/puppet-foreman_proxy, pull requests merged in 2020-08, with the labels that each got.

#609 Fix tftp on RedHat 8
  manifests/params.pp
Labels: Bug, Needs testing

#607 don't fail on upcase() when domain fact is undefined
  manifests/init.pp
  manifests/params.pp
  manifests/proxydns.pp
Labels: Needs testing

#610 Release 15.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing

#611 Set up HTTPClients in DHCP
  examples/httpboot.pp
  manifests/proxydhcp.pp
  spec/acceptance/httpboot_spec.rb
  templates/httpboot_dhcp_class.erb
Labels: Needs testing

#612 Release 15.1.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog
