Repository theforeman/puppet-foreman_proxy, pull requests merged in 2020-05, with the labels that each got.

#578 Allow extlib 5.x
  metadata.json
Labels: Needs testing

#589 Modulesync: Require voxpupuli-test 1.4
  Gemfile
Labels: Needs testing

#591 Drop unused MySQL module fixture
  .fixtures.yml
Labels: Needs testing

#592 Fixes #29690 - install shimx64.efi and shim.efi
  manifests/tftp/netboot.pp
  spec/classes/foreman_proxy__tftp__netboot_spec.rb
Labels: Needs testing

#582 Fixes #29213 - Support el8
  .sync.yml
  .travis.yml
  metadata.json
Labels: Needs re-review, Needs testing

#595 Update module dependencies to allow EL8 supported versions
  metadata.json
Labels: Needs testing

#596 correct needed foreman dependency
  metadata.json
Labels: Needs testing

#594 Release 14.0.0
  CHANGELOG.md
  metadata.json
Labels: Needs re-review, Needs testing, skip-changelog
