Repository theforeman/puppet-foreman_proxy, pull requests merged in 2021-04, with the labels that each got.

#658 Mark compatible with Foreman 17.x
  metadata.json
Labels: Needs testing

#657 Remove Puppet version check
  manifests/params.pp
Labels: Needs testing

#638 Update Pulp plugin to drop Pulp 2
  manifests/plugin/pulp.pp
  manifests/plugin/pulp/params.pp
  spec/classes/foreman_proxy__plugin__pulp_spec.rb
  templates/plugin/pulp.yml.erb
  templates/plugin/pulpnode.yml.erb
Labels: Backwards incompatible, Needs testing

#659 Bump version to 18.0.0
  metadata.json
Labels: Needs testing

#662 Refs #31893 - make ansible callback configurable
  manifests/plugin/ansible.pp
  manifests/plugin/ansible/params.pp
  templates/plugin/ansible.cfg.erb
Labels: Enhancement, Needs testing

#656 adding smart_proxy_dns_route53 plugin support
  manifests/plugin/dns/route53.pp
  spec/classes/foreman_proxy__plugin__dns__route53_spec.rb
  templates/dns.yml.erb
  templates/plugin/dns_route53.yml.erb
Labels: Needs testing

#663 Refs #31893 - correct default value
  manifests/plugin/ansible/params.pp
Labels: Bug, Needs testing

#652 Support Puppet 7
  metadata.json
Labels: Enhancement, Needs testing

#660 Release 18.0.0
  CHANGELOG.md
Labels: Needs testing, skip-changelog

#665 Allow puppet-puppet < 16.0.0
  metadata.json
Labels: Bug, Needs testing

#664 don't manage runner repo on Debian
  manifests/plugin/ansible.pp
  manifests/plugin/ansible/params.pp
  manifests/plugin/ansible/runner.pp
  spec/acceptance/ansible_spec.rb
  spec/classes/foreman_proxy__plugin__ansible_spec.rb
Labels: Enhancement, Needs testing

#668 Release 18.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog
