Repository theforeman/puppet-foreman_proxy, pull requests merged in 2021-11, with the labels that each got.

#707 Refs #33760 - Add reports proxy plugin
  manifests/plugin/ansible.pp
  manifests/plugin/ansible/params.pp
  manifests/plugin/reports.pp
  spec/classes/foreman_proxy__plugin__ansible_spec.rb
  spec/classes/foreman_proxy__plugin__reports_spec.rb
  templates/plugin/ansible.cfg.erb
  templates/plugin/reports.yml.erb
Labels: Needs testing

#713 Drop Ubuntu 18.04 support
  metadata.json
  spec/classes/foreman_proxy__plugin__discovery_spec.rb
  spec/classes/foreman_proxy__spec.rb
  spec/classes/foreman_proxy__tftp_spec.rb
Labels: Needs testing, Backwards incompatible

#706 Fixes #33688 - Set max_files to unlimited for TFTP directories
  manifests/tftp.pp
  metadata.json
Labels: Needs testing, Enhancement

#712 Bump to 20.0.0 and update compatibility table
  README.md
  metadata.json
Labels: Needs testing, Enhancement

#709 Release 20.0.0
  CHANGELOG.md
Labels: Needs testing, skip-changelog

#714 Fixes #33864 - disable registration by default
  manifests/init.pp
  spec/classes/foreman_proxy__register__spec.rb
  spec/classes/foreman_proxy__spec.rb
Labels: Needs testing, Bug

#716 Allow theforeman/foreman 19.0.0
  metadata.json
Labels: Needs testing, Enhancement

#717 Release 20.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog
