Repository theforeman/puppet-foreman_proxy, pull requests merged in 2021-03, with the labels that each got.

#649 Update Github Actions workflow
  .github/workflows/acceptance.yml
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  .github/workflows/unit.yml
  Gemfile
Labels: Modulesync, Needs testing, Not yet reviewed

#654 Release 17.1.1
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog

#651 Add shellhooks plugin
  manifests/plugin/shellhooks.pp
  spec/classes/foreman_proxy__plugin__shellhooks_spec.rb
  templates/plugin/shellhooks.yml.erb
Labels: Needs testing
