Repository theforeman/puppet-foreman_proxy, pull requests merged in 2021-07, with the labels that each got.

#686 Allow puppet-dns 9.0.0
  metadata.json
Labels: Needs testing

#685 Allow puppet-tftp 7.0.0
  metadata.json
Labels: Needs testing, Not yet reviewed

#689 Allow puppet-dhcp 7.0.0
  metadata.json
Labels: Needs testing

#690 Fixes #32710 - tftp support for Rocky Linux and AlmaLinux
  manifests/tftp/netboot.pp
  metadata.json
  spec/classes/foreman_proxy__tftp__netboot_spec.rb
Labels: Needs testing

#677 Remove Foreman repository parameters
  manifests/init.pp
  manifests/install.pp
  spec/classes/foreman_proxy__spec.rb
Labels: Backwards incompatible, Needs testing, Not yet reviewed

#634 Move all static vars from params to init
  manifests/init.pp
  manifests/params.pp
Labels: Needs re-review, Needs testing

#691 Release 19.0.0
  CHANGELOG.md
Labels: Needs testing

#693 Fixes #33162 - Set value for Ansible collections_paths
  manifests/plugin/ansible.pp
  manifests/plugin/ansible/params.pp
  spec/classes/foreman_proxy__plugin__ansible_spec.rb
  templates/plugin/ansible.cfg.erb
Labels: Enhancement
