Repository theforeman/puppet-foreman_proxy, pull requests merged in 2022-10, with the labels that each got.

#775 Fixes #35396 - allow non-root user to read Salt master config file
  manifests/plugin/salt.pp
Labels: Needs testing

#778 Bring config files closer to packaged versions
  spec/classes/foreman_proxy__spec.rb
  templates/bmc.yml.erb
  templates/dhcp_isc.yml.erb
  templates/dns.yml.erb
  templates/logs.yml.erb
  templates/puppet.yml.erb
  templates/puppet_proxy_puppet_api.yml.erb
  templates/puppetca.yml.erb
  templates/puppetca_token_whitelisting.yml.erb
  templates/realm.yml.erb
  templates/realm_freeipa.yml.erb
  templates/registration.yml.erb
  templates/settings.yml.erb
  templates/tftp.yml.erb
Labels: Needs testing, Enhancement

#788 Change module feature default to capitalize
  manifests/module.pp
  manifests/module/bmc.pp
  manifests/module/dhcp.pp
  manifests/module/dns.pp
  manifests/module/tftp.pp
  spec/defines/foreman_proxy_module_spec.rb
Labels: Backwards incompatible
