Repository theforeman/puppet-foreman_proxy, pull requests merged in 2022-04, with the labels that each got.

#736 Add acceptance tests for remote_execution::ssh
  examples/remote_execution_ssh.pp
  spec/acceptance/remote_execution_ssh_spec.rb
Labels: Needs testing

#738 Fixes #34774 - don't expose tftp syslinux files directly
  manifests/globals.pp
  manifests/init.pp
  manifests/params.pp
  manifests/tftp.pp
  spec/classes/foreman_proxy__spec.rb
Labels: Needs testing, Backwards incompatible

#740 add missing class param training comma
  manifests/plugin/remote_execution/ssh.pp
Labels: Needs testing

#739 add foreman_proxy::plugin::remote_execution::ssh::ssh_log_level param
  examples/remote_execution_ssh-ssh_log_level.pp
  manifests/plugin/remote_execution/ssh.pp
  spec/acceptance/remote_execution_ssh_spec.rb
  spec/classes/foreman_proxy__plugin__remote_execution__ssh_spec.rb
  spec/type_aliases/sshloglevel_spec.rb
  templates/plugin/remote_execution_ssh.yml.erb
  types/sshloglevel.pp
Labels: Needs testing

#741 Bump master to 22.0.0
  metadata.json
Labels: Needs testing

#734 Rename remote_execution plugin to foreman_proxy::plugin::remote_execution
  examples/remote_execution_script-ssh_log_level.pp
  examples/remote_execution_script.pp
  examples/remote_execution_ssh-ssh_log_level.pp
  examples/remote_execution_ssh.pp
  manifests/plugin/remote_execution/script.pp
  spec/acceptance/remote_execution_script_spec.rb
  spec/classes/foreman_proxy__plugin__remote_execution__script_spec.rb
  templates/plugin/remote_execution_ssh.yml.erb
Labels: Needs testing, Backwards incompatible

#743 Update README.md compatability
  README.md
Labels: Needs testing

#737 Fixes #34239: Add pull-mqtt support to smart_proxy_remote_execution
  .fixtures.yml
  examples/remote_execution_script_pull_mqtt.pp
  manifests/plugin/remote_execution/mosquitto.pp
  manifests/plugin/remote_execution/script.pp
  spec/acceptance/remote_execution_script_pull_mqtt_spec.rb
  templates/plugin/foreman.acl.epp
Labels: Needs testing

#747 Support BMC redfish integration
  manifests/init.pp
  manifests/install.pp
  spec/classes/foreman_proxy__spec.rb
  templates/bmc.yml.erb
Labels: Needs testing, Enhancement

#744 Add support for cleaning up mosquitto when switching to SSH
  manifests/plugin/remote_execution/mosquitto.pp
  manifests/plugin/remote_execution/script.pp
  spec/acceptance/remote_execution_script_pull_mqtt_spec.rb
  spec/classes/foreman_proxy__plugin__remote_execution__mosquitto_spec.rb
  spec/classes/foreman_proxy__plugin__remote_execution__script_spec.rb
Labels: Needs testing

#746 Release 22.0.0
  CHANGELOG.md
Labels: Needs testing

#748 allow theforeman/foreman 20.x
  metadata.json
Labels: Needs testing, Enhancement
