Repository theforeman/puppet-foreman_proxy, pull requests merged in 2022-05, with the labels that each got.

#750 correctly clean up mosquitto inbetween tests
  spec/acceptance/ansible_spec.rb
  spec/acceptance/basic_spec.rb
  spec/acceptance/dns_spec.rb
  spec/acceptance/dual_spec.rb
  spec/acceptance/dynflow_spec.rb
  spec/acceptance/http_spec.rb
  spec/acceptance/journald_spec.rb
  spec/acceptance/netboot_spec.rb
  spec/acceptance/remote_execution_script_pull_mqtt_spec.rb
  spec/acceptance/remote_execution_script_spec.rb
  spec/support/acceptance/cleanup.rb
Labels: Needs testing, skip-changelog

#749 Release 22.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing

#752 add missing dep on puppet/mosquitto
  metadata.json
Labels: Needs testing, Bug

#753 Ensure certs were deployed before we try to source them
  manifests/plugin/remote_execution/mosquitto.pp
  spec/classes/foreman_proxy__plugin__remote_execution__mosquitto_spec.rb
Labels: Needs testing, Bug

#754 Release 22.1.1
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#755 also chain private keys from puppet-certs correctly
  manifests/plugin/remote_execution/mosquitto.pp
  spec/classes/foreman_proxy__plugin__remote_execution__mosquitto_spec.rb
Labels: Needs testing, Bug

#756 notify the mosquitto service of changes to the acl and certs
  manifests/plugin/remote_execution/mosquitto.pp
  spec/classes/foreman_proxy__plugin__remote_execution__mosquitto_spec.rb
Labels: Needs testing, Bug

#758 ensure config notifies mosquitto
  manifests/plugin/remote_execution/script.pp
  spec/classes/foreman_proxy__plugin__remote_execution__script_spec.rb
Labels: Needs testing, Bug

#759 Release 22.1.3
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog
