Repository theforeman/puppet-foreman_proxy, pull requests merged in 2022-02, with the labels that each got.

#704 Fixes #33549 - Add parameter dhcp_ipxefilename to set a value for DHCP's iPXE filename
  manifests/init.pp
  manifests/proxydhcp.pp
  spec/classes/foreman_proxy__proxydhcp__spec.rb
Labels: Needs testing

#723 puppet/extlib: Allow 6.x
  metadata.json
Labels: Needs testing

#725 Refs #34239 - Use mode parameter for remote_execution_ssh plugin
  manifests/plugin/remote_execution/ssh.pp
  spec/classes/foreman_proxy__plugin__remote_execution__ssh_spec.rb
  templates/plugin/remote_execution_ssh.yml.erb
Labels: Needs re-review, Needs testing, Backwards incompatible

#724 Release 21.0.0
  CHANGELOG.md
  HISTORY.md
  README.md
  metadata.json
Labels: Needs testing, skip-changelog

#730 Release 19.0.1
  CHANGELOG.md
  metadata.json
Labels: Needs re-review, Needs testing, skip-changelog
