Repository theforeman/puppet-foreman_proxy, pull requests merged in 2022-03, with the labels that each got.

#731 Switch to gha-puppet for CI
  .github/workflows/ci.yml
  Gemfile
Labels: Needs testing, Modulesync

#727 Move REX ssh key management into separate class
  manifests/plugin/remote_execution/ssh.pp
  manifests/plugin/remote_execution/ssh/keys.pp
  spec/classes/foreman_proxy__plugin__remote_execution__ssh__keys_spec.rb
Labels: Needs testing, Enhancement

#732 [REX SSH Plugin] Don't manage net-ssh-krb package
  manifests/plugin/remote_execution/ssh.pp
  spec/classes/foreman_proxy__plugin__remote_execution__ssh_spec.rb
Labels: Needs testing, Bug
