Repository theforeman/puppet-foreman_proxy, pull requests merged in 2022-09, with the labels that each got.

#780 Drop ansible-runner repository management
  README.md
  manifests/plugin/ansible.pp
  manifests/plugin/ansible/runner.pp
  spec/classes/foreman_proxy__plugin__ansible_spec.rb
Labels: Backwards incompatible

#782 Add a test that ansible-runner is working
  spec/acceptance/ansible_spec.rb
Labels: Not yet reviewed

#630 Refs #31118 - Remove daemon option from settings.yaml
  spec/classes/foreman_proxy__spec.rb
  templates/settings.yml.erb
Labels: Needs testing, Backwards incompatible
