Repository theforeman/puppet-foreman_proxy, pull requests merged in 2022-08, with the labels that each got.

#767 Drop EL7 support
  README.md
  manifests/params.pp
  metadata.json
  spec/acceptance/journald_spec.rb
  spec/defines/foreman_proxy_plugin_spec.rb
  spec/spec_helper_acceptance.rb
  spec/support/plugin.rb
Labels: Needs testing, Backwards incompatible

#768 Refs #35184 - Drop puppetca_http_api provider
  manifests/config.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_proxy__spec.rb
  templates/puppetca.yml.erb
  templates/sudo.erb
  templates/sudo_augeas.erb
Labels: Needs testing, Backwards incompatible

#769 Release 23.0.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#770 Allow theforeman/foreman 21.x
  metadata.json
Labels: Needs testing, Not yet reviewed, Bug

#771 Release 23.0.1
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog

#772 manage discovery plugin config file
  examples/discovery.pp
  manifests/plugin/discovery.pp
  spec/acceptance/discovery_spec.rb
  spec/classes/foreman_proxy__plugin__discovery_spec.rb
  templates/plugin/discovery.yml.erb
Labels: Needs testing

#776 Drop reports proxy plugin
  manifests/plugin/ansible.pp
  manifests/plugin/ansible/params.pp
  manifests/plugin/reports.pp
  spec/classes/foreman_proxy__plugin__ansible_spec.rb
  spec/classes/foreman_proxy__plugin__reports_spec.rb
  templates/plugin/ansible.cfg.erb
  templates/plugin/reports.yml.erb
Labels: Needs testing, Backwards incompatible
