Repository theforeman/puppet-foreman_proxy, pull requests merged in 2023-05, with the labels that each got.

#804 Simplify grub_efi_path on redhat family
  manifests/tftp/netboot.pp
Labels: Enhancement

#805 Refs #36345 - Raise minimum Puppet version to 7.0.0
  metadata.json
Labels: Backwards incompatible

#806 Mark compatible with theforeman/dns 10.x & theforeman/dhcp 9.x
  metadata.json
Labels: Enhancement

#807 Mark compatible with theforeman/foreman 23.x
  metadata.json
Labels: Not yet reviewed, Enhancement
