Repository theforeman/puppet-foreman_proxy, pull requests merged in 2024-02, with the labels that each got.

#828 Make exception to grub_efi_path for OracleLinux
  manifests/tftp/netboot.pp
Labels: Bug

#829 Add HDM smart proxy
  manifests/plugin/hdm.pp
  spec/classes/foreman_proxy__plugin__hdm_spec.rb
  templates/plugin/hdm.yml.erb
Labels: Enhancement

#831 Release 25.3.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
